name: ChatTags
version: 1.1.0
main: com.johannfullhd.chattags.ChatTags
api-version: 1.13
author: Johann-FullHD
description: A comprehensive chat tag customization plugin for Spigot servers
website: https://github.com/Johann-FullHD

commands:
  tag:
    description: Main command for managing chat tags
    usage: /<command> [set|color|toggle|preview|clear|list|clear-all|disable-all|help]
    aliases: [chattag, tags]

permissions:
  chattags.*:
    description: Grants all ChatTags permissions
    children:
      chattags.use: true
      chattags.set: true
      chattags.color: true
      chattags.toggle: true
      chattags.clear: true
      chattags.admin: true
      chattags.bypass.cooldown: true
    default: op
  
  chattags.use:
    description: Allows using the /tag command
    default: true
  
  chattags.set:
    description: Allows setting a custom tag
    default: true
  
  chattags.color:
    description: Allows changing tag color
    default: true
  
  chattags.toggle:
    description: Allows toggling tag on/off
    default: true
  
  chattags.clear:
    description: Allows clearing your tag
    default: true
  
  chattags.admin:
    description: Allows administrative functions
    default: op

  chattags.bypass.cooldown:
    description: Allows bypassing tag change cooldown
    default: false